export const TOGGLE_SHOW_MUSIC_BAR = 'TOGGLE_SHOW_MUSIC_BAR';
export const TOGGLE_SHOW_NAVIGATION_BAR = 'TOGGLE_SHOW_NAVIGATION_BAR';
export const SET_NAVIGATION_BAR_TITLE = 'SET_NAVIGATION_BAR_TITLE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SAVE_USERINFO = 'SAVE_USERINFO';
